from tkinter import*
root=Tk()
root.title("Visual Studio Code")
root.geometry("500x500")
menu_bar=Menu(root)
file=Menu(menu_bar,tearoff=0)
menu_bar.add_cascade(label="File",menu=file)
file.add_cascade(label="New Text File         Ctrl+N")
file.add_cascade(label="New file...   Ctrl+Alt+Windows+N")
file.add_cascade(label="New Window      Ctrl+Shift+N")
file.add_separator()
file.add_cascade(label="Open File...     Ctrl+O")
file.add_cascade(label="Open Folder...   Ctrl+K C trl+O")
file.add_cascade(label="Exit",command=root.destroy)
Edit=Menu(menu_bar,tearoff=0)
menu_bar.add_cascade(label="Edit",menu=Edit)
Edit.add_cascade(label="Undo")
Edit.add_cascade(label="Redo")
Edit.add_separator()
Edit.add_cascade(label="Cut")
Edit.add_cascade(label="Copy")
Edit.add_cascade(label="Paste")
Edit.add_cascade(label="Select all...")
Edit.add_separator()
Edit.add_cascade(label="Find")
Edit.add_cascade(label="Replace")
Help=Menu(menu_bar,tearoff=0)
menu_bar.add_cascade(label="Help",menu=Help)
Help.add_cascade(label="Tk Help")
Help.add_cascade(label="Troubleshoot")
Help.add_cascade(label="About")
Help.add_separator()
Help.add_cascade(label="Feedback")
root.config(menu=menu_bar)
root.mainloop()